apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dank-city-ingress
spec:
  rules:
  - host: dev.dank.city
    http:
      paths:
      - backend:
          serviceName: dank-city
          servicePort: 8000
  - host: bar.foo.com
    http:
      paths:
      - backend:
          serviceName: dank-city
          servicePort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: dank-city-svc
  labels:
    app: dank-city-svc
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: dank-city

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dank-city
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dank-city
  template:
    metadata:
      labels:
        app: dank-city
    spec:
      containers:
      - name: dank-city
        image: ${DEPLOY_REPO}:${DOCKER_TAG}
        env:
        - name: SENTRY_DSN
          value: ${SENTRY_DSN}
        - name: SENTRY_ENVIRONMENT
          value: ${NAMESPACE}
